### ISSUE TITLE
QueryException when creating a new field

### ISSUE THREAD

**Issue by bloveless** [anomalylabs/pages-module#18]
Completely fresh install. I deleted the database and all the files. git reset --hard HEAD and reinstalled.

![screen shot 2015-07-01 at 11 38 27 am](https://cloud.githubusercontent.com/assets/535135/8460920/d3c679b4-1fe5-11e5-8564-3721c13ee3a7.png)

This was the very first thing I did. Went to Pages -> Fields -> New Field -> Chose Editor (English and Spanish are enabled by default) Name = Content all the rest are defaulted. Press Save. Got the screenshot above. But the field still saved to the database.

When editing and saving the field again it saves just fine and the values update correctly.

NOTE: It works just fine when I fill in both the spanish and english content.

**Comment by RyanThompson** [comment]
Ya.. So this is one of those things where I got caught in the middle.

I need to change the dependency on translated content and only require the base language.

The migrations for fields n shit can have that removed (make the nullable) if you know where. Otherwise I can do it shortly.


Ryan Thompson
President / CEO
AnomalyLabs, Inc.
www.anomaly.is<http://www.anomaly.is>

t (877) 705-0806
m (309) 752-8581



On Jul 1, 2015, at 12:43 PM, bloveless <notifications@github.com<mailto:notifications@github.com>> wrote:


Completely fresh install. I deleted the database and all the files. git reset --hard HEAD and reinstalled.

[screen shot 2015-07-01 at 11 38 27 am]<https://cloud.githubusercontent.com/assets/535135/8460920/d3c679b4-1fe5-11e5-8564-3721c13ee3a7.png>

This was the very first thing I did. Went to Pages -> Fields -> New Field -> Chose Editor (English and Spanish are enabled by default) Name = Content all the rest are defaulted. Press Save. Got the screenshot above. But the field still saved to the database.

When editing and saving the field again it saves just fine and the values update correctly.

NOTE: It works just fine when I fill in both the spanish and english content.

**Comment by RyanThompson** [comment]
Pull installer module and reinstall unfortunately - this one is on the base tables.. :-(

**Comment by bloveless** [comment]
Will do!

**Comment by RyanThompson** [comment]
Reinstall after wiping database and updateing - this should be good to go
